name: Lymra-Ont
channels:
  - conda-forge
  - bioconda
  - daler
  - defaults
dependencies:
  - samtools
  - bwa
  - bowtie2
  - sickle
  - fastqc
  - python=3
  - minimap2
  - ragtag
  - abricate
  - spades
  - minimap2
  - mummer
  - mash
  - mafft
  - prokka
  - quast
  - perl-padwalker
  - perl-db-file
  - porechop
  - sickle-trim
  - pip
  - homopolish
  - medaka
  - gw
  - bcftools
  - bzip2
  - freebayes
  - htslib
  - medaka
  - xorg-kbproto
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - xorg-libice
  - yaml
  - zipp
  - zlib
  - zstd
  - brotlipy
  - dsdp
  - fftw
  - gnutls
  - ipython_genutils
  - keras-applications
  - libllvm10
  - lz4-c
  - metis
  - nettle
  - qualimap
  - pillow
  - sip
  - toml
  - toposort
  - tornado
  - traitlets
  - gotree
  - busco=5.4.2
  - kraken2
  - bioconda::homopolish>=0.3.3
  - pip:
      - numpy
      - matplotlib
      - matplotlib-venn
      - biopython
      - dREP
      - snipit
      - appdirs==1.4.3
      - args==0.1.0
      - attrs==19.3.0
      - babel==2.8.0
      - bcbio-gff==0.6.6
      - binlorry==1.3.0a1
      - biopython==1.76
      - boto3==1.12.39
      - botocore==1.15.39
      - cachetools==4.1.0
      - chardet==3.0.4
      - clint==0.5.1
      - configargparse==1.2.1
      - crypto==1.4.1
      - cycler==0.10.0
      - cython==0.29.16
      - decorator==4.4.2
      - docutils==0.16
      - git+https://github.com/artic-network/Porechop.git@v0.3.2pre
      - gitdb==4.0.4
      - gitpython==3.1.1
      - google-api-core==1.17.0
      - google-api-python-client==1.8.2
      - google-auth-httplib2==0.0.3
      - google-auth-oauthlib==0.4.1
      - google-auth==1.14.1
      - googleapis-common-protos==1.51.0
      - httplib2==0.17.3
      - image==1.5.31
      - jdcal==1.4.1
      - idna==2.9
      - importlib-metadata==1.6.0
      - ipython-genutils==0.2.0
      - jmespath==0.9.5
      - jsonschema==3.2.0
      - jupyter-core==4.6.3
      - kiwisolver==1.2.0
      - matplotlib==3.2.1
      - medaka==1.0.1
      - more-itertools==8.2.0
      - naked==0.1.31
      - nbformat==5.0.5
      - netifaces==0.10.9
      - nextstrain-augur==7.0.2
      - nextstrain-cli==1.16.2
      - numpy==1.18.2
      - oauthlib==3.1.0
      - openpyxl==3.0.3
      - packaging==20.3
      - pandas==1.0.3
      - phylo-treetime==0.7.4
      - pluggy==0.13.1
      - pycryptodome==3.9.7
      - pytest==5.4.1
      - protobuf==3.11.3
      - pyasn1-modules==0.2.8
      - pyasn1==0.4.8
      - pyparsing==2.4.7
      - pyqt5-sip==4.19.18
      - pyqtwebengine==5.12.1
      - pyrsistent==0.16.0
      - pysam==0.15.2
      - pyyaml==5.3.1
      - ratelimiter==1.2.0.post0
      - requests-oauthlib==1.3.0
      - requests==2.23.0
      - rethinkdb==2.3.0.post6
      - rsa==4.0
      - s3transfer==0.3.3
      - scipy==1.4.1
      - setuptools==46.1.3
      - shellescape==3.8.1
      - smmap==3.0.2
      - snakemake==5.10.0
      - ttkthemes==3.1.0
      - tkcalendar==1.6.1
      - toposort==1.5
      - traitlets==4.3.3
      - tk-html-widgets==0.4.0
      - tkinterhtml==0.7
      - tqdm==4.46.0
      - wcwidth==0.1.9
      - uritemplate==3.0.1
      - urllib3==1.25.8
      - wrapt==1.12.1
      - zipp==3.1.0

