name: Lymra-Ont
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - samtools
  - bcftools
  - freebayes
  - bioconda::flye=2.9
  - libcuckoo
  - intervaltree
  - lemon
  - minimap2
  - samtools
  - bioconda::homopolish>=0.3.3
  - bioconda::medaka=1.4.3
  - porechop
  - fastp
pip:
  - matplotlib
  - pysam 
  - python 




