name: Lymra-Ont
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - samtools
  - bcftools
  - freebayes
  - bioconda::flye=2.9
  - libcuckoo
  - intervaltree
  - lemon
  - minimap2
  - samtools
  - bioconda::homopolish>=0.3.3
  - porechop
  - fastp
  - kraken2
  - pip:
    - matplotlib
    - pysam 
    - python 
    - medaka
    - zlib1g-dev 
    - libbz2-dev 
    - liblzma-dev 
    - libffi-dev 
    - libncurses5-dev
    - libcurl4-gnutls-dev 
    - libssl-dev 
    - curl 
    - make 
    - cmake 
    - wget 
    - python3-all-dev
    - python-virtualenv
    - tabix
    - g++
    - bzip2




