name: monkeypox-lymra
channels:
  - conda-forge
  - bioconda
  - daler
  - defaults
dependencies:
  - samtools
  - bwa
  - sickle
  - fastqc
  - python=3
  - minimap2
  - ragtag
  - abricate
  - mlst
  - spades
  - minimap2
  - mummer
  - mash
  - mafft
  - prokka
  - quast
  - perl-padwalker
  - perl-db-file
  - porechop
  - sra-tools
  - sickle-trim
  - pip
  - homopolish
  - medaka
  - gw
  - pip:
      - numpy
      - matplotlib
      - matplotlib-venn
      - biopython
      - dREP
      - snipit

