name: Lymra-Ont
channels:
  - conda-forge
  - bioconda
  - defaults
  - daler
  - anaconda
dependencies:
  - bioconda::flye=2.9
  - libcucim
  - intervaltree
  - lemon
  - minimap2
  - samtools
  - porechop
  - homopolish
  - kraken2
  - bioconda::medaka=1.7.2
  - pip
  - busco
  - cmake
  - pip:
    - bgzip

