name: Lymra-Ont
channels:
  - conda-forge
  - bioconda
  - daler
  - defaults
dependencies:
  - samtools
  - bwa
  - bowtie2
  - sickle
  - fastqc
  - python=3
  - minimap2
  - ragtag
  - abricate
  - spades
  - minimap2
  - mummer
  - mash
  - mafft
  - prokka
  - quast
  - perl-padwalker
  - perl-db-file
  - porechop
  - sickle-trim
  - pip
  - homopolish
  - medaka
  - gw
  - bcftools
  - bzip2
  - freebayes
  - htslib
  - medaka
  - busco
  - kraken2
  - pip:
      - numpy
      - matplotlib
      - matplotlib-venn
      - biopython
      - dREP
      - snipit
      

