name: conda-flye
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - bioconda::flye=2.9
  - libcuckoo
  - intervaltree
  - lemon
  - minimap2
  - samtools
  - porechop

